### ISSUE TITLE
Pattern thumbnails should have pointer cursor

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-theme-directory#138] opened 2024-06-18 07:58 UTC
The patterns on theme pages are interactive, but the `default` cursor seems to imply they are not:

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/8c8d51a3-7683-4082-a2e4-6620f3302151)

We could change that to `pointer` to make it more clear you can click and test those patterns.

Related: https://github.com/WordPress/wporg-theme-directory/issues/128

**Comment by ryelle** [comment] 2024-06-18 15:00
This is a duplicate of #128, the same point was raised there.

**Closed as not planned by ryelle** 2024-06-18 15:00 UTC
