### ISSUE TITLE
Permalink footer should go edge to edge

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-theme-directory#63] opened 2024-05-13 13:44 UTC
Pagination looks good. The element itself, including the gray border above, should go edge to edge.

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/a6a59a36-ea56-460b-b145-c2ebfadcabd9)

**Comment by ryelle** [comment] 2024-05-13 15:06
This is a duplicate of #58 (as in, it has the same root cause).

**Closed as not planned by ryelle** 2024-05-13 15:06 UTC
