### ISSUE TITLE
Theme Translations should be viewable directly

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-theme-directory#28] opened 2023-02-17 08:18 UTC
Moving from meta trac: https://meta.trac.wordpress.org/ticket/5925

**Is your feature request related to a problem? Please describe.**
> When you look at an overview page of a plugin, you can quickly see at the right side in which languages it's translated.

> Yet, on theme pages, you only get a button that goes to translate.wordpress.org

**Describe the solution you'd like**
> Why the inconstancy? I think it could be helpful to see if a theme is translated or not like with the plugins.

**Comment by ryelle** [comment] 2024-04-16 21:39
Duplicate of meta ticket https://meta.trac.wordpress.org/ticket/1383, we can use this issue to track.

**Closed as completed** 2024-05-17 16:51 UTC
Labels: [Component] Blocks
